object Deps {
    const val kore_ktx = "androidx.core:core-ktx:${Versions.core_ktx}"
    const val lifecycle_runtime = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.lifecycle_runtime}"
    const val activity_compose = "androidx.activity:activity-compose:${Versions.activity_compose}"
    const val compose_bom = "androidx.compose:compose-bom:${Versions.compose_bom}"
    const val compose_ui = "androidx.compose.ui:ui"
    const val compose_ui_graphics = "androidx.compose.ui:ui-graphics:${Versions.compose}"
    const val ui_tooling_preview = "androidx.compose.ui:ui-tooling-preview:${Versions.compose}"
    const val material3 = "androidx.compose.material3:material3:${Versions.material}"
    const val junit = "junit:junit:${Versions.junit}"
    const val test_ext_junit = "androidx.test.ext:junit:${Versions.test_ext_junit}"
    const val espresso = "androidx.test.espresso:espresso-core:${Versions.espresso}"
    const val ui_test_junit4 = "androidx.compose.ui:ui-test-junit4"
    const val ui_tooling = "androidx.compose.ui:ui-tooling"
    const val ui_test_manifest = "androidx.compose.ui:ui-test-manifest"

    // Dagger and Hilt
    const val hilt_android = "com.google.dagger:hilt-android:2.47"
    const val hilt_compiler = "com.google.dagger:hilt-compiler:2.47"
    const val hilt_android_compiler = "com.google.dagger:hilt-android-compiler:2.47"
    const val hilt_compiler_android = "androidx.hilt:hilt-compiler:1.0.0"
    const val hilt_navigation_compose = "androidx.hilt:hilt-navigation-compose:1.0.0"

    const val mockk = "io.mockk:mockk:${Versions.mockk}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    const val retrofit_gson = "com.squareup.retrofit2:converter-gson:${Versions.retrofit_gson}"
    const val okhttp = "com.squareup.okhttp3:okhttp:${Versions.okhttp}"
    const val okhttpLogging = "com.squareup.okhttp3:logging-interceptor:${Versions.okhttpLogging}"
    const val test_compose_bom = "androidx.compose:compose-bom:${Versions.test_compose_bom}"
    const val appcompat = "androidx.appcompat:appcompat:${Versions.appcompat}"
    const val material = "com.google.android.material:material:${Versions.material}"
}
